version: '3.5'
services:
    db:
      image: postgres:alpine
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: '1234'
        POSTGRES_DB: clevertec
      ports:
        - "5432:5432"
      volumes: 
        - db:/var/lib/postgresql/data
    redis:
      image: redis
      restart: always
      ports:
        - "6379:6379"
    authserver:
      build:
        context: ./AuthServer
      container_name: authserver
      restart: always
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/clevertec
      ports:
        - "8090:8090"
      depends_on:
        - db
        - final-project

    config-server:
      build:
        context: ./ConfigServer
      container_name: config-server
      restart: always
      ports:
      - "8888:8888"

    final-project:
      build:
        context: ./MainNewsService
      container_name: final-project
      restart: always
      ports:
        - "8080:8080"
      depends_on:
        - db
        - config-server

      environment:
        CONFIGHOST: http://config-server:8888
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/clevertec
        FEIGN_URL: http://authserver:8090
        ACTIVE: dev
        SPRING_DATA_REDIS_HOST: redis
volumes:
  db:


